### ISSUE TITLE
[BUG] Live Preivew is not working 

### ISSUE THREAD

**Issue by yenaingtun-dev** [myanmarcyberyouths/mCal#226]
**Describe the bug**
[myanmar-calendar.vercel.app](https://myanmar-calendar.vercel.app/) is not working. 

**To Reproduce**

1. Click the link [myanmar-calendar.vercel.app](https://myanmar-calendar.vercel.app/)
4. See error 404

**Expected behavior**
Expected to see some information.

**Screenshots**
![image](https://github.com/myanmarcyberyouths/mCal/assets/59411234/91ff5237-4186-469d-96d0-17a80ba78635)

**Comment by theaungmyatmoe** [comment]
Thank you for the kind feedback, we highly recommended you to use the desktop version of our app instead of web app.
