### ISSUE TITLE
Question about keeping the app purely Frontend

### ISSUE THREAD

**Issue by YakuBrangJa** [myanmarcyberyouths/mCal#47]
Is there a plan to keep this app purely frontend, or are there any intentions to incorporate a backend for storing user data in the future?

**Comment by amm834** [comment]
I am currently thinking about that what tech stack should we use for that?

**Comment by YakuBrangJa** [comment]
I can't say for sure. I only have experience with Laravel on the backend side.

**Comment by amm834** [comment]
I'm currently considering about Laravel (or) Nest JS for the sake of backend development. However, I don't even have any plan for that why should we devlope backend for what purpose just in case I want to consider about. We do need to consider functionalities before diving into it to reduce our development load.

**Comment by YakuBrangJa** [comment]
Yes, I agree with you. For now, majority of the features can be done on frontend alone. Let's save it for the future in case if we want to transform it into productivity-oriented application.

**Comment by amm834** [comment]
Yes, we should only take care of our frontend part for now.
